title: Adebisi Damola # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://www.linkedin.com/in/adedamola-adebisi-55814a33/">View My LinkedIn Profile</a> 
  <br><br>
  
theme: jekyll-theme-minimal
